### PR TITLE
rodentQC

### PR DESCRIPTION
**Pull request by eilidhmacnicol**
This PR puts in place the foundation to extend MRIQC to other populations, including rodents.

Still to do:

- [x] Improve segmentation
- [x] Test alternative EPI masking methods
- [x] ~~Finalise~~ Initial head mask parameters for rats
- [ ] ~~Improving the reportlets for rodent FOVs (although maybe this requires some more work from the niworkflows end)~~ -> moving to NiWorkflows
- [ ] ~~Add a test for rats (WDYT?)~~ -> will open a separate issue for this

For future, it might be worth establishing a dictionary or a set of JSON files that set template choices for each species available in TemplateFlow.

NB: I tried to push to this as a feature branch, rather than straight to master, but I didn't have the credentials.

### CODE REVIEW

**Review by oesteban — APPROVED** [review]
Looks awesome - thanks for this!

**Comment by oesteban** [comment]
Hey @eilidhmacnicol, I've just cut 22.0.0rc1 and rebased this branch to current master. This is to say, I'm happy to help here and do whatever you need to get this to the finish line.

It feels that the better segmentation, the tests, and the better parameters of the head mask can/should be addressed in separate PRs. The improvements to the reportlets pertain to niworkflows/nirodents.

**Comment by eilidhmacnicol** [comment]
Hi @oesteban - I've added the option for Atropos segmentation, and it's looking much better now.

I agree that segmentation and headmasking can be improved in later commits when we encounter further test data. Marking as ready to merge now.

**Comment by oesteban** [comment]
One more for style -- can you run

```
black mriqc/
```

?

**Comment by eilidhmacnicol** [comment]
@oesteban - tests are looking good, but I've just realised an issue: I see the NiWorkflows version has been pinned, but `NiRodents` and `artsBrainExtraction` currently uses a feature branch of NiWorkflows so this will need to be updated for a Docker image.

**Comment by oesteban** [comment]
We will need to finalize spitting out the brain extraction from niworkflows in order to be able to use the new package :(

The alternative is too dirty for an official MRIQC release.

**Comment by eilidhmacnicol** [comment]
Okay - some very good news. The NiWorkflows pin issue was (thankfully) a false alarm. I ran an image built on mriqc 22.0.0rc with the necessary changes from here and nipreps/nirodents#55 built on top and it ran with no issues.  

At this stage, the blockers for this PR's merge are:

_related to `NiRodents`_
- [ ] nipreps/niworkflows#694 to be accepted and the subsequent minor release of `NiWorkflows`
- [ ] Cut a new tag for `NiRodents` on PyPi pinning the new `NiWorkflows` release
- [ ] Pin the `NiRodents` version here

_related to `DiPy`_
- [ ] `dipy 1.4.1` breaks NiPype (See nipy/nipype#2402), so unless `nipype >= 1.7.1` then `dipy <= 1.4.0` for rodents

**Comment by eilidhmacnicol** [comment]
I think the tests failing are unrelated to the changes made here and might be beyond the scope of this PR. WDYT @oesteban? Is it time to merge?

**Comment by oesteban** [comment]
> I think the tests failing are unrelated to the changes made here and might be beyond the scope of this PR. WDYT @oesteban? Is it time to merge?

You are going to break master, but considering the type of error it is fair to say that the problem is beyond the scope of this PR. So go ahead and merge.

The reason why this is failing is that we probably need to pin `jinja2` with some upper bound version. We should do that quickly after your PR so that dependency errors don't start snowballing.

**Comment by oesteban** [comment]
Actually, you can't merge, I believe. I'm giving you permissions right now - please merge yourself (I believe one should merge their own PRs whenever that is possible/allowed).

**Pull request merged**
